# Generated by Django 4.2.23 on 2025-07-09 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiornoNonPrenotabile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Portate',
            },
        ),
        migrations.CreateModel(
            name='Tavolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('piccolo', 'Piccolo (1,3 persone)'), ('grande', 'Grande (3-6 persone)')], max_length=10)),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('capienza_massima', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25, null=True)),
                ('cognome', models.CharField(max_length=25, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('saldo_punti', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Utenti',
            },
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ora', models.TimeField()),
                ('numero_persone', models.PositiveIntegerField()),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('tavoli_assegnati', models.ManyToManyField(blank=True, to='accounts.tavolo')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Piatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ingredienti', models.CharField(blank=True, max_length=500, null=True)),
                ('prezzo', models.FloatField(null=True)),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='piatti/')),
                ('portata', models.ManyToManyField(to='accounts.portata')),
            ],
            options={
                'verbose_name_plural': 'Piatti',
            },
        ),
        migrations.CreateModel(
            name='Ordinazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField(default=1)),
                ('completato', models.BooleanField(default=False)),
                ('piatto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.piatto')),
                ('utente', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ordinazioni',
            },
        ),
    ]
